# Generated by Django 2.2.6 on 2019-11-22 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20)),
                ('group_id', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('friends', models.ManyToManyField(blank=True, related_name='_user_friends_+', to='dashboard.User')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('trans_type', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Group')),
                ('participants', models.ManyToManyField(to='dashboard.User')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='users',
            field=models.ManyToManyField(to='dashboard.User'),
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lent', models.FloatField()),
                ('creditor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_creditor', to='dashboard.User')),
                ('debitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction_debitor', to='dashboard.User')),
                ('trans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Transaction')),
            ],
            options={
                'unique_together': {('trans', 'creditor', 'debitor')},
            },
        ),
    ]
