# Generated by Django 2.2.7 on 2019-11-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='transactiondetail',
            old_name='group_id',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='transactiondetail',
            old_name='trans_id',
            new_name='trans',
        ),
        migrations.RenameField(
            model_name='transactiondetail',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterUniqueTogether(
            name='groups',
            unique_together={('group_id', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='transactiondetail',
            unique_together={('trans', 'user')},
        ),
    ]
