# Generated by Django 2.2.7 on 2019-11-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20191123_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dp',
            field=models.ImageField(upload_to='profile_pic'),
        ),
    ]
