# Generated by Django 2.2.7 on 2019-11-24 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191124_0749'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='comments',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
