# Generated by Django 2.2.7 on 2019-11-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20191106_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='participants',
            field=models.ManyToManyField(to='dashboard.User'),
        ),
    ]
