# Generated by Django 2.2.7 on 2019-11-25 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191124_0655'),
        ('dashboard', '0005_transaction_comments'),
    ]

    operations = [
    ]
