# Generated by Django 2.2.7 on 2019-11-07 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_transaction_participants'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='group',
        ),
        migrations.AddField(
            model_name='transaction',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Group'),
        ),
    ]
